sudo: required
dist: precise
services:
  - docker
before_install:
  - sudo apt-get install jq
env:
  - ADDON="mopidy"
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - ./build.sh $ADDON